version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test .

  build_and_push:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true    

      - run:
          name: Build and push Docker image
          command: |
            export TAG=$(date +'%Y%m%d%H%M%S')
            echo "Tag: $TAG"
            docker build -t deepakprasad/todo-react-app:$TAG .
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push deepakprasad/todo-react-app:$TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
